version: "3"

services:

  web:
    build: ./docker/web
    ports:
      - 11080:80
    volumes:
      - ./src:/var/www/html/
    privileged: true
    command: /sbin/init
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.30.0.2

  db:
    build: ./docker/db
    ports:
      - 53306:3306
    volumes:
      - ./dbdata:/tmp/dbdata
    env_file:
      - ./docker/db/conf/dev.env
    privileged: true
    command: /sbin/init
    # environment:
      # MYSQL_ROOT_PASSWORD: password
    networks:
      app_net:
        ipv4_address: 172.30.0.3

networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
